version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "US/Eastern"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
