name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 8 * * 6'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test
        run: go test -v ./...

      - name: Format
        run: |
          gofmt -w -s .
          git diff --exit-code

      - name: Vet
        run: go vet ./...

      - name: Lint
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@v0.4.7
          staticcheck -f stylish ./...
