name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 8 * * 6'

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Go test
        run: go test -v ./...

      - name: Go format
        run: |
          gofmt -w -s .
          git diff --exit-code

      - name: Go vet
        run: go vet ./...

      - name: Go lint
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@v0.4.7
          staticcheck -f stylish ./...

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python lint
        uses: chartboost/ruff-action@v1

      - name: Python format
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'

  other:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run extra CI checks
        run: python etc/ci-check.py
