name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 8 * * 6'

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test
        run: go test -v ./...

      - name: Format
        run: |
          gofmt -w -s .
          git diff --exit-code

      - name: Vet
        run: go vet ./...

      - name: Lint
        uses: dominikh/staticcheck-action@v1
        with:
          version: 'v0.4.7'
          install-go: false

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'

      - name: Lint
        uses: chartboost/ruff-action@v1

  other:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run extra CI checks
        run: python etc/ci-check.py
